### ISSUE TITLE
我想问下 .gitignore 跑哪儿去啦？

### ISSUE THREAD

**Issue by haruue** [PinkDBoat/BattleCity_2#1]
你们的 Android Studio 建项目不带这东西么？

**Comment by Bllinger** [comment]
(⊙o⊙)…现在添加上去了。。。push的时候没发现

**Comment by haruue** [comment]
但是被 ignore 的东西仍然在仓库里。。试试看怎么移除他们吧。。。
另外建议用命令行的 git 而不是 Android Studio 的版本控制插件，不然你会经常忘记 add 东西。。。

**Comment by Bllinger** [comment]
谢谢，越神提醒。。。
我是用的git bush的。。。只是在add的时候用了‘ * ’
然后就被忽略了。。。
